tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "shivammathur/php"
brew "composer"
brew "dnsmasq"
brew "ffmpeg"
brew "gh"
brew "gifski"
brew "imagemagick"
brew "jq"
brew "mas"
brew "neofetch"
brew "nginx"
brew "php@8.1", link: true
brew "pinentry-mac"
brew "pngquant"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "wget"
cask "1password"
cask "adguard"
cask "affinity-designer"
cask "affinity-photo"
cask "affinity-publisher"
cask "bartender"
cask "capcut"
cask "chatgpt"
cask "cloudflare-warp"
cask "dbngin"
cask "docker"
cask "figma"
cask "font-aileron"
cask "font-cascadia-code"
cask "font-fira-code"
cask "font-hack"
cask "font-inter"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "gpg-suite"
cask "insomnia"
cask "iterm2"
cask "jetbrains-toolbox"
cask "lm-studio"
cask "notion"
cask "obs"
cask "openkey"
cask "shottr"
cask "slack"
cask "spotify"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "zed"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "DaVinci Resolve", id: 571213070
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Termius", id: 1176074088
mas "The Unarchiver", id: 425424353
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "caponetto.vscode-diff-viewer"
vscode "cjhowe7.laravel-blade"
vscode "dbaeumer.vscode-eslint"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "mehedidracula.php-namespace-resolver"
vscode "mrmlnc.vscode-duplicate"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-powertoys"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.remote-explorer"
vscode "neilbrayfield.php-docblocker"
vscode "rebornix.toggle"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "streetsidesoftware.code-spell-checker-vietnamese"
vscode "vscodevim.vim"
vscode "vue.volar"
vscode "xdebug.php-debug"
